### ISSUE TITLE
xetazr.in error

### ISSUE THREAD

**Issue by padsley** [I-Thompson/fresco#1]
xetazr.in test case fails with attached output.

I can't currently work out what parameter MLOC is so fixing that problem is not currently possible.

[xetazr_out.txt](https://github.com/I-Thompson/fresco/files/5304707/xetazr_out.txt)

**Comment by I-Thompson** [comment]
I fixed this problem in the github version of Fresco earlier this year.
Could you please try running the current github version, and let me know if still a problem.

**Comment by padsley** [comment]
The version which I can find on the repo was last updated in November 2017 (unless I'm looking in the wrong place: master branch in tests/xetazr.in)?

**Comment by I-Thompson** [comment]
I mean: the code was updated

**Comment by padsley** [comment]
Oh. Mea culpa. That works. Thanks.
